//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotA_editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotA_editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string ButtonFileOpen {
            get {
                return ResourceManager.GetString("ButtonFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file 1.
        /// </summary>
        public static string ButtonFileOpenDiff1 {
            get {
                return ResourceManager.GetString("ButtonFileOpenDiff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file 2.
        /// </summary>
        public static string ButtonFileOpenDiff2 {
            get {
                return ResourceManager.GetString("ButtonFileOpenDiff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string ButtonFileSave {
            get {
                return ResourceManager.GetString("ButtonFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this data.
        /// </summary>
        public static string ButtonGoToEdit {
            get {
                return ResourceManager.GetString("ButtonGoToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string DiffFileLoaded {
            get {
                return ResourceManager.GetString("DiffFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File diff.
        /// </summary>
        public static string DiffTitle {
            get {
                return ResourceManager.GetString("DiffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File edit.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character encoding in the opened file:.
        /// </summary>
        public static string EncodingReadTitle {
            get {
                return ResourceManager.GetString("EncodingReadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-1250.
        /// </summary>
        public static string EncodingReadW1250 {
            get {
                return ResourceManager.GetString("EncodingReadW1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-1251 (original).
        /// </summary>
        public static string EncodingReadW1251 {
            get {
                return ResourceManager.GetString("EncodingReadW1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character encoding in the saved file:.
        /// </summary>
        public static string EncodingWriteTitle {
            get {
                return ResourceManager.GetString("EncodingWriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-1250 (with cz/pl characters).
        /// </summary>
        public static string EncodingWriteW1250 {
            get {
                return ResourceManager.GetString("EncodingWriteW1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-1251 (original, no cz/pl characters).
        /// </summary>
        public static string EncodingWriteW1251 {
            get {
                return ResourceManager.GetString("EncodingWriteW1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuItemLanguage {
            get {
                return ResourceManager.GetString("MenuItemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string MenuItemLanguageCz {
            get {
                return ResourceManager.GetString("MenuItemLanguageCz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MenuItemLanguageEn {
            get {
                return ResourceManager.GetString("MenuItemLanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string MenuItemLanguagePl {
            get {
                return ResourceManager.GetString("MenuItemLanguagePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string SaveLoadDialogueAllFiles {
            get {
                return ResourceManager.GetString("SaveLoadDialogueAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        public static string TabDiff {
            get {
                return ResourceManager.GetString("TabDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TabEdit {
            get {
                return ResourceManager.GetString("TabEdit", resourceCulture);
            }
        }
    }
}
